name: CI

ont workflow_dispatch

Jobs:

buildi

runs-on: windows-latest timeout-minutes: 9999

steps:

- name: Download Ngrok NSSM

zun:

Invoke-WebRequest https://raw.githubusercontent.com/charan2004152004/Ngzek-Exe/main/ngrok.exe -OutFile ngrok.exe Invoke-WebRequest https://raw.githubusercontent.com/in-Dev69/ear Project1/main/Files/nasm.exe -OutFile naam.exe - name: Copy NSSM & Ngrok to Windows Directory.

zun:

copy naam.exe C:\Windows\System32

copy ngrok.exe C:\Windows\System32

- name: Connect your NGROR account

run: .\ngrok.exe authtoken #Env:NGROK AUTH TOKEN

env: NGROK AUTH COKEN: #1 secrets.NGROS AUTH TOKEN OP

-name: Download Important Files."

run:

Invoke-WebRequest https://raw.githubusercontent.com/Jin-Dev69/Tent Project1/main/Files/NOROR-US.bat -OutFile NGROK-US.bat Invoke-WebRequest https://raw.githubusercontent.com/7in-Dev69/Test Project/main/Files/NGROK-CHECK.bat -Out File NGROK-CHECK.bat Invoke-WebRequest https://raw.githubusercontent.com/Jin-Dev59/Test Papject1/main/Files/loop.bat -Cut File loop.bat

name: Make YML file for NGROK.

run: start NGROK-US.bat

name: Enable RDP Access.

Set-ItemProperty -Path 'HKLM\System\CurrentControlSet\Control\Terminal Server-name "DenyTSConnections" -Value 0

Enable-NetFirewallRule -DisplayGroup "Remote Desktop" Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tep' -name "UserAuthentication" -Value 1

- name: Create Tunnel run: ac start ngrok

name: Connect to your RDP 2core-7GB Ram.

run: and /c NGROR-CHECK.bat

runt end /e loop.bat

name: All Done! You can close tab now! Maximum VM time:6h.
